



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration Form</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }

        .form-container {
            width: 400px;
            margin: 50px auto;
            background: white;
            padding: 25px;
            border-radius: 8px;
            box-shadow: 0 0 10px gray;
        }

        h2 {
            text-align: center;
        }

        label {
            font-weight: bold;
            display: block;
            margin-top: 10px;
        }

        input, select {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            width: 100%;
            padding: 10px;
            margin-top: 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>

</head>

<body>

<div class="form-container">

    <h2>Create User Account</h2>

    <form action="insert_user.php" method="POST">

        <!-- user_id is auto increment, no need to enter -->
         <label for="fname">FIRST NAME</label>
        <input type="text" id="fname" name="fname" 
               placeholder="Enter first name" required>

               <label for="email">LAST NAME</label>
        <input type="text" id="lname" name="lname" 
               placeholder="Enter last name" required>

        <label for="email">Email Address (Username)</label>
        <input type="email" id="email" name="email" 
               placeholder="Enter email address" required>


        <label for="password">Password</label>
        <input type="password" id="password" name="password" 
               placeholder="Enter password" required>


        <label for="role">User Role</label>
        <select id="role" name="role" required>
            <option value="">--Select Role--</option>
            <option value="student">Student</option>
            <option value="teacher">Teacher</option>
            <option value="admin">Admin</option>
        </select>


        <label for="status">Account Status</label>
        <select id="status" name="status">
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
        </select>


        <!-- created_at is automatically generated by database -->

        <button type="submit" name="user" class="btn btn-primary">Create User</button>

    </form>

</div>

</body>
</html>